config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update] do
      resources :order_details, only: [:update]
    end
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    resources :items, only: [:index,:show]
    get 'members/my_page' => 'members#show',as:'my_page'
    get 'members/information/edit' => 'members#edit',as:'members_edit'
    patch 'members/information' => 'members#update',as:'members_update'
    get 'members/confirm' => 'members#confirm',as:'members_confirm'
    patch 'members/withdraw' => 'members#withdraw',as:'members_withdraw'
    resources :cart_items, only: [:index,:update,:create,:destroy]
    delete 'cart_items' => 'cart_items#destroy_all',as:'destroy_all'
    get 'orders/thanks' => 'orders#thanks',as:"orders_thanks"
    resources :orders, only: [:new,:create,:index,:show]
    post 'orders/confirm' => 'orders#confirm',as:"orders_confirm"

    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  get '/searches' => 'searches#search', as:'search'
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :member

  validates :address, presence:true
  validates :postal_code, presence:true
  validates :shipping_name, presence:true
  # エラーメッセージは未実装です(時間に余裕があればつける)

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + shipping_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :member
  belongs_to :item
  
  validates :quantity, numericality: { in: 1..50 }

  def subtotal
  #税込み価格と個数の掛け算です。
    item.with_tax_price.floor*quantity.to_i
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_many :orders, through: :order_items
  belongs_to :genre
  has_one_attached :image

  with_options presence: true do
   validates :name
   validates :introduction
   validates :price
   validates :image
 end
 validates :is_active, inclusion: { in: [true, false] }

  def get_item_image(width,height)
    image.variant(resize_to_limit: [width,height]).processed
  end

  #商品単価の3桁ごとに「,」を表示するメソッドです(税抜)
  #下記のコードはstring型になります。計算には使用できません。(山田)
  #いらないかも、、、
  def number_to_currency
    price.to_s(:delimited)
  end

  #税込み価格の計算です。floorは小数点を表示しないよう記述しております。
  def with_tax_price
    (price*1.1).floor
  end
  
  # 注文商品の合計金額(請求金額　-　送料)
  def sum_of_price
    item.price*quantity
  end

  def self.looks(word)
    @items = Item.where("name LIKE?","%#{word}%")
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence:true
  validates :first_name, presence:true
  validates :last_name_kana, presence:true
  validates :first_name_kana, presence:true
  VALID_POSTAL_CODE_REGEX = /\A\d{7}\z/
  validates :postal_code, presence:true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :address, presence:true
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :phone_number, presence:true, format: { with: VALID_PHONE_REGEX }
  validates :is_deleted, inclusion: [true, false]

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :member

  enum payment_method: ["クレジットカード", "銀行振込"]

  enum order_status: {payment_waiting: 0,  payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
  def set_date
    created_at.strftime("%Y/%-m/%-d/ %-H:%M:%S")
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

  validates :quantity, numericality: { in: 1..50 }
  enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to request.referer
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(update_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def update_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end

  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @members = Member.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path(@member)
    else
      render 'edit'
    end
  end

  private

  def member_params
    params.require(:member).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:phone_number,:email,:is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @items = Item.looks(params[:word])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/members/_edit.html.erb
          <tr>
            <td scope="col" style="width: 20%" class="align-middle">氏名</td>
            <td scope="col" style="width: 30%"><%= f.text_field :last_name, autofocus: true, class: "form-control" %></td>
            <td scope="col" style="width: 30%"><%= f.text_field :first_name, autofocus: true, class: "form-control" %></td>
            <td scope="col" style="width: 10%"></td>
          </tr>
          <tr>
            <td class="align-middle">フリガナ</td>
            <td><%= f.text_field :last_name_kana, autofocus: true, class: "form-control" %></td>
            <td><%= f.text_field :first_name_kana, autofocus: true, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="align-middle">郵便番号</td>
            <td><%= f.text_field :postal_code, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="align-middle">住所</td>
            <td colspan="3"><%= f.text_field :address, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="align-middle">電話番号</td>
            <td><%= f.text_field :phone_number, class: "form-control" %></td>
          </tr>
          <tr>
            <td class="align-middle">メールアドレス</td>
            <td><%= f.text_field :email, class: "form-control" %></td>
          </tr>

app/views/admin/members/edit.html.erb
<div class="container mx-auto">
  <%= render "admin/admin/shared/error_messages", resource: @member %>
  <div class="row mt-3">
    <div class="col-md-10 mx-auto ">
      <label class=" h4 bg-light pr-3 pl-3"><%= "#{@member.last_name}#{@member.first_name}" %>さんの会員情報編集</label>
      <%= form_with model: @member, url: admin_member_path, method: :patch do |f| %>
        <table class="table table-borderless mt-3 bg-light">
          <tr>
            <td scope="col" style="width: 20%">会員ID</td>
            <td scope="col" style="width: 30%"><%= @member.id %></td>
            <td scope="col" style="width: 30%"></td>
            <td scope="col" style="width: 10%"></td>
          </tr>
          <%= render 'edit', f: f %>
          <tr>
            <td class="align-middle">会員ステータス</td>
            <td>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, '有効' %>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, '退会' %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit '変更を保存',  class: "btn btn-success" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/members/index.html.erb
<div class="container mx-auto">
  <div class="row mt-3">
    <div class="col-md-12 mx-auto">
      <label class="h4 bg-light pr-3 pl-3">会員一覧</label>
      <table class="table table-secondary table-striped mt-3">
        <thead>
          <tr class="text-center">
            <th scope="col" style="width: auto">会員ID</th>
            <th scope="col" style="width: auto">氏名</th>
            <th scope="col" style="width: auto">メールアドレス</th>
            <th scope="col" style="width: auto%">ステータス</th>
          </tr>
        </thead>
        <tbody class="table-light">
          <% @members.each do |member| %>
            <tr class="text-center">
              <!--会員ID-->
              <td><%= member.id %></td>
              <!--会員名-->
              <td>
                <%= link_to "#{member.last_name} #{member.first_name}", admin_member_path(member) %>
              </td>
              <!--メールアドレス-->
              <td><%= member.email %></td>
              <!--会員ステータス-->
              <td>
                <% if member.is_deleted == false %>
                  <span class="text-success">有効</span>
                <% elsif %>
                  <span>退会</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <%= paginate(@members) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container mx-auto">
  <div class="row mt-3">
    <div class="col-md-10 mx-auto">
      <label class="h4 bg-light pr-3 pl-3"><%= "#{@member.last_name}#{@member.first_name}" %>さんの会員詳細</label>
      <table class="table text-left bg-light table-borderless mt-3">
        <tr>
          <td cope="col" style="width: 20%">会員ID</td>
          <td cope="col" style="width: 50%"><%= @member.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= "#{@member.last_name} #{@member.first_name}" %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= "#{@member.last_name_kana} #{@member.first_name_kana}" %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @member.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @member.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @member.phone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @member.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <% if @member.is_deleted == false %>
              <span class="text-success">有効</span>
            <% elsif %>
              <span>退会</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= link_to '編集する', edit_admin_member_path(@member), class: "btn btn-success mr-3" %>
            <%= link_to '注文履歴一覧を見る', admin_path, class: "btn btn-primary" %>
          </td>
          <td></td>
        </tr>
      </table>
    </div>
  </div>
</div>