config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update] do
      resources :order_details, only: [:update]
    end
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    resources :items, only: [:index,:show]
    get 'members/my_page' => 'members#show',as:'my_page'
    get 'members/information/edit' => 'members#edit',as:'members_edit'
    patch 'members/information' => 'members#update',as:'members_update'
    get 'members/confirm' => 'members#confirm',as:'members_confirm'
    patch 'members/withdraw' => 'members#withdraw',as:'members_withdraw'
    resources :cart_items, only: [:index,:update,:create,:destroy]
    delete 'cart_items' => 'cart_items#destroy_all',as:'destroy_all'
    get 'orders/thanks' => 'orders#thanks',as:"orders_thanks"
    resources :orders, only: [:new,:create,:index,:show]
    post 'orders/confirm' => 'orders#confirm',as:"orders_confirm"

    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  get '/searches' => 'searches#search', as:'search'
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :member

  validates :address, presence:true
  validates :postal_code, presence:true
  validates :shipping_name, presence:true
  # エラーメッセージは未実装です(時間に余裕があればつける)

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + shipping_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :member
  belongs_to :item
  
  validates :quantity, numericality: { in: 1..50 }

  def subtotal
  #税込み価格と個数の掛け算です。
    item.with_tax_price.floor*quantity.to_i
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_many :orders, through: :order_items
  belongs_to :genre
  has_one_attached :image

  with_options presence: true do
   validates :name
   validates :introduction
   validates :price
   validates :image
 end
 validates :is_active, inclusion: { in: [true, false] }

  def get_item_image(width,height)
    image.variant(resize_to_limit: [width,height]).processed
  end

  #商品単価の3桁ごとに「,」を表示するメソッドです(税抜)
  #下記のコードはstring型になります。計算には使用できません。(山田)
  #いらないかも、、、
  def number_to_currency
    price.to_s(:delimited)
  end

  #税込み価格の計算です。floorは小数点を表示しないよう記述しております。
  def with_tax_price
    (price*1.1).floor
  end
  
  # 注文商品の合計金額(請求金額　-　送料)
  def sum_of_price
    item.price*quantity
  end

  def self.looks(word)
    @items = Item.where("name LIKE?","%#{word}%")
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence:true
  validates :first_name, presence:true
  validates :last_name_kana, presence:true
  validates :first_name_kana, presence:true
  VALID_POSTAL_CODE_REGEX = /\A\d{7}\z/
  validates :postal_code, presence:true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :address, presence:true
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :phone_number, presence:true, format: { with: VALID_PHONE_REGEX }
  validates :is_deleted, inclusion: [true, false]

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :member

  enum payment_method: ["クレジットカード", "銀行振込"]

  enum order_status: {payment_waiting: 0,  payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
  def set_date
    created_at.strftime("%Y/%-m/%-d/ %-H:%M:%S")
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

  validates :quantity, numericality: { in: 1..50 }
  enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to request.referer
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(update_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def update_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end

  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
   @order = Order.find(params[:id])
   @order_item = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
    if @order.update(order_params)
      @order_items.update_all(production_status: 1 ) if @order.order_status == "payment_confirmation"
    end
    redirect_to request.referer
  end


  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @items = Item.looks(params[:word])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <%= render "admin/admin/shared/error_messages", resource: @genre %>
  <div class="row">
    <div class="col-md-12 mt-3">
      <label class="h4 bg-light pr-3 pl-3 mt-3 mb-0">ジャンル編集</label>
      <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch, local:true do |f| %>
        <table class="table table-borderless mt-4" style="width: 50%">
          <tr>
            <td class="align-bottom" scope="col" style="width: 20%"><%= f.label "ジャンル名" %></td>
            <td class="align-middle" scope="col" style="width: 20%"><%= f.text_field :name, placeholder: "ジャンル名" %></td>
            <td class="text-center" scope="col" style="width: 30%"><%= f.submit "変更を保存", class: "btn btn-success" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <label class="h4 bg-light pr-3 pl-3 mt-3">ジャンル一覧・追加</label>
      <%= form_with model: @genre, url: admin_genres_path, method: :post, local:true do |f| %>
        <table class="table table-borderless mt-4" style="width: 50%">
          <tr>
            <td class="align-bottom mb-0" scope="col" style="width: 20%"><%= f.label :name, "ジャンル名" %></td>
            <td class="align-middle" scope="col" style="width: 20%"><%= f.text_field :name, placeholder: "ジャンル名" %></td>
            <td class="text-center" scope="col" style="width: 30%"><%= f.submit "新規登録", class: "btn btn-success" %></td>
          </tr>
        </table>
      <% end %>
      <div class="row">
        <table class="table mt-4" style="width: 400px">
          <thead class="bg-light">
            <tr class="text-center">
              <th scope="col" style="width: 250px">ジャンル</th>
              <th scope="col" style="width: 150px"></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
              <tr class="bg-white">
                <td><%= genre.name %></td>
                <td class="text-center"><%= link_to "編集する" , edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mx-auto mt-3">
    <div class= "col-7 mt-3 mx-auto">
       <label class="h4 bg-light pr-3 pl-3 mp-0">商品編集</label>
       <%= render "admin/admin/shared/error_messages", resource: @item %>
       <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
      <table class="table mt-4 table-borderless bg-white">
           <tr>
             <td><%= f.label :image, '商品画像' %></td>
             <td> <%= f.file_field :image, accept: "image/*" %></td>
           </tr>
           <tr>
             <td><%= f.label :name, '商品名' %></td>
             <td><%= f.text_field :name, class:"form-control" %></td>
           </tr>
           <tr>
             <td><%= f.label :introduction, '商品説明' %></td>
             <td><%= f.text_area :introduction, rows: "5", class:"form-control" %></td>
           </tr>
           <tr>
             <td><%= f.label :genre_id, 'ジャンル' %></td>
             <td><%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"} %></td>
           </tr>
           <tr>
             <td><%= f.label :price, '税抜価格' %></td>
             <td> <%= f.number_field :price, class:"form-control-sm" %>円</td>
           </tr>
           <tr>
             <td>
               <%= f.label :is_active, '販売ステータス' %>
              </td>
              <td>
               <%= f.radio_button :is_active, true %>
               <%= f.label :is_active, '販売中', value: true %>
               <%= f.radio_button :is_active, false %>
               <%= f.label :is_active, '販売停止中', value: false %>
             </td>
           </tr>
          <tr>
            <td></td>
            <td>
              <%= f.submit '変更を保存', class: "btn btn-success w-50" %>
            </td>
            <td></td>
          </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container mt-3">
  <div class="row mx-auto">
    <div class="col-md-10 mx-auto">
      <div>
        <label class="h4 bg-light pr-3 pl-3">商品一覧</label>
      </div>
        <div class="text-right">
           <%= link_to new_admin_item_path, class: "btn btn-lg btn-{themecolor}.rounded-circle.p-0 secondary " do %>
             <i class="fas fa-plus-circle"></i>
           <% end %>
         </div>
        <table class="table mt-3 text-center  bg-white">
          <thead class="table-secondary">
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th></th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= item.number_to_currency %></td>
              <td>
                <%= item.genre.name %>
              </td>
              <td></td>
              <td>
                <% if item.is_active == true %>
                  <span class="text-success">販売中</span>
                <% else %>
                 <span class="text-secondary">販売停止中</span>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div>
          <%= paginate @items %>
        </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
   <div class="row">
     <div class="col-8 mt-3 mx-auto">
        <label class="h4 bg-light pr-3 pl-3 mp-0">商品新規登録</label>
          <%= form_with model: @item, url: admin_items_path, method: :post, local: true do |f| %>
          <table class="table mt-4 table-borderless bg-white">
            <div>
              <%= render "admin/admin/shared/error_messages", resource: @item %>
              <tr>
                <td><%= f.label :image, '商品画像' %></td>
                <td><%= f.file_field :image, accept: "image/*" %></td>
              </tr>
              <tr>
                <td><%= f.label :name, '商品名' %></td>
                <td><%= f.text_field :name, class:"form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :introduction, '商品説明' %></td>
                <td><%= f.text_area :introduction, rows: "5", class:"form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :genre_id, 'ジャンル' %></td>
                <td><%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"}, class:"form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :price, '税抜価格' %></td>
                <td><%= f.number_field :price, class:"form-control-sm" %>円</td>
              </tr>
              <tr>
                  <td>
                    <%= f.label :is_active, '販売ステータス' %>
                  </td>
                  <td>
                    <%= f.radio_button :is_active, true %>
                    <%= f.label :is_active, '販売中', value: true %>
                    <%= f.radio_button :is_active, false %>
                    <%= f.label :is_active, '販売停止中', value: false %>
                  </td>
              </tr>
              <tr>
                <td></td>
                <td><%= f.submit '新規登録', class: "btn btn-success w-40" %></td>
                <td></td>
              </tr>
            </div>
          </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-3 mx-auto">
  <div class="row">
    <div>
      <label class="h4 bg-light pr-3 pl-3 mp-0">商品詳細</label>
    　<div class="col-4">
        <%= image_tag @item.get_item_image(280,230) %>
      </div>
    </div>
    <div class='col-6'>
      <table class="table table-borderless bg-white">
         <tr>
           <td>商品名</td>
           <td><%= @item.name %></td>
        　</tr>
         <tr>
           <td>商品説明</td>
           <td><%= @item.introduction %></td>
         </tr>
         <tr>
           <td>ジャンル</td>
           <td><%= @item.genre.name %></td>
         </tr>
         <tr>
           <td>税込価格<br>(税抜価格)</td>
           <td><%= @item.with_tax_price.to_s(:delimited) %> ( <%= @item.price.to_s(:delimited) %>)円</td>
         </tr>
         <tr>
           <td>販売ステータス</td>
           <td>
            <% if @item.is_active == true %>
             <span class="text-success font-weight-bold">販売中</span>
            <% else %>
             <span class="text-secondary font-weight-bold">販売停止中</span>
            <% end %>
           </td>
         </tr>
         <tr>
            <td></td>
            <td> <%= link_to '編集する', edit_admin_item_path(@item.id), class: "btn btn-success w-40" %></td>
            <td></td>
         </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <label class="h4 bg-light mt-3 pr-3 pl-3 mp-0">注文履歴詳細</label>
    <div class="row">
      <div class="col-5 text-left">
      <table class="table table-borderless mt-4 bg-white">
        <tr>
          <th>購入者</th>
          <td><%= link_to "#{@order.member.last_name} #{@order.member.first_name}", admin_member_path(@order.member) %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.post_code.to_s.insert(3, "-") %> <%= @order.address %><br><%= @order.shipping_name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td><%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
              <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
              <%= f.submit "更新", class:"btn btn-success btn-sm" %>
              <% end %>
          </td>
        </tr>
      </table>
      </div>
    </div>
      <div class="row">
        <div class="col-8">
            <table class="table mt-4 bg-white">
              <thead class="table-secondary">
                <tr>
                  <th>商品名</th>
                  <th>単価（税込）</th>
                  <th>数量</th>
                  <th>小計</th>
                  <th>製作ステータス</th>
                </tr>
              </thead>
              <% @order_item.each do |order_item| %>
              <tbody>
                <tr>
                  <td><%= order_item.item.name %></td>
                  <td><%= order_item.tax_in_price.to_s(:delimited) %></td>
                  <td><%= order_item.quantity %></td>
                  <td>
                    <% subtotal = (order_item.tax_in_price*order_item.quantity).to_s(:delimited) %>
                    <%= subtotal %>
                  </td>
                  <td>
                    <%= form_with model: [@order,order_item], url: admin_order_order_detail_path(@order,order_item), method: :patch do |f| %>
                    <%= f.select :production_status, OrderItem.production_statuses.keys.map {|k| [I18n.t("enums.order_item.production_status.#{k}"), k]} %>
                    <%= f.submit "更新", class:"btn btn-success btn-sm" %>
                    <% end %>
                  </td>
                </tr>
              </tbody>
              <% end %>
            </table>
        </div>
        <div class="col-3 d-flex align-items-end">
            <table class="table table-borderless mt-4 bg-white">
              <tr>
                <th class="pr-1">商品合計</th>
                <td class="text-right"><%= (@order.total_payment - @order.postage).to_s(:delimited) %>円</td>
              </tr>
              <tr>
                <th class="pr-1">送料</th>
                <td class="text-right"><%= @order.postage %>円</td>
              </tr>
              <tr>
                <th class="pr-1">請求金額合計</th>
                <td class="text-right font-weight-bold">
                  <%= @order.total_payment.to_s(:delimited) %>円
                </td>
              </tr>
            </table>
        </div>
      </div>
</div>