config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update] do
      resources :order_details, only: [:update]
    end
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    resources :items, only: [:index,:show]
    get 'members/my_page' => 'members#show',as:'my_page'
    get 'members/information/edit' => 'members#edit',as:'members_edit'
    patch 'members/information' => 'members#update',as:'members_update'
    get 'members/confirm' => 'members#confirm',as:'members_confirm'
    patch 'members/withdraw' => 'members#withdraw',as:'members_withdraw'
    resources :cart_items, only: [:index,:update,:create,:destroy]
    delete 'cart_items' => 'cart_items#destroy_all',as:'destroy_all'
    get 'orders/thanks' => 'orders#thanks',as:"orders_thanks"
    resources :orders, only: [:new,:create,:index,:show]
    post 'orders/confirm' => 'orders#confirm',as:"orders_confirm"

    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  get '/searches' => 'searches#search', as:'search'
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :member

  validates :address, presence:true
  validates :postal_code, presence:true
  validates :shipping_name, presence:true
  # エラーメッセージは未実装です(時間に余裕があればつける)

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + shipping_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :member
  belongs_to :item
  
  validates :quantity, numericality: { in: 1..50 }

  def subtotal
  #税込み価格と個数の掛け算です。
    item.with_tax_price.floor*quantity.to_i
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_many :orders, through: :order_items
  belongs_to :genre
  has_one_attached :image

  with_options presence: true do
   validates :name
   validates :introduction
   validates :price
   validates :image
 end
 validates :is_active, inclusion: { in: [true, false] }

  def get_item_image(width,height)
    image.variant(resize_to_limit: [width,height]).processed
  end

  #商品単価の3桁ごとに「,」を表示するメソッドです(税抜)
  #下記のコードはstring型になります。計算には使用できません。(山田)
  #いらないかも、、、
  def number_to_currency
    price.to_s(:delimited)
  end

  #税込み価格の計算です。floorは小数点を表示しないよう記述しております。
  def with_tax_price
    (price*1.1).floor
  end
  
  # 注文商品の合計金額(請求金額　-　送料)
  def sum_of_price
    item.price*quantity
  end

  def self.looks(word)
    @items = Item.where("name LIKE?","%#{word}%")
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence:true
  validates :first_name, presence:true
  validates :last_name_kana, presence:true
  validates :first_name_kana, presence:true
  VALID_POSTAL_CODE_REGEX = /\A\d{7}\z/
  validates :postal_code, presence:true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :address, presence:true
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :phone_number, presence:true, format: { with: VALID_PHONE_REGEX }
  validates :is_deleted, inclusion: [true, false]

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :member

  enum payment_method: ["クレジットカード", "銀行振込"]

  enum order_status: {payment_waiting: 0,  payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
  def set_date
    created_at.strftime("%Y/%-m/%-d/ %-H:%M:%S")
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

  validates :quantity, numericality: { in: 1..50 }
  enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to request.referer
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(update_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def update_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end

  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @items = Item.looks(params[:word])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/homes/top.html.erb
<div class="container mt-3">
  <div class="row mx-auto">
    <div class="col-md-10 mx-auto">
      <label class="h4 bg-white pr-3 pl-3">注文履歴一覧</label>
      <p class="text-success"><%= flash[:alert] %></p>
      <table class="table mt-3 text-center">
        <thead>
          <tr class="bg-secondary text-white">
            <th scope="col" style="width: 30%">購入日時</th>
            <th scope="col" style="width: 30%">購入者</th>
            <th scope="col" style="width: 20%">注文個数</th>
            <th scope="col" style="width: 20%">注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr class="bg-white">
              <!--order.rbで記載したset_dateで日時を表示できる-->
              <td><%= link_to order.set_date, admin_order_path(order) %></td>
              <td><%= order.member.last_name %><%= order.member.first_name %></td>
              <td>
                <%= order.order_items.sum(:quantity) %>
              </td>
              <td><%= order.order_status_i18n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <%= paginate(@orders) %>
      </div>
    </div>
  </div>
</div>

app/views/searches/_search.html.erb
<div class="container">
  <span></span>
  <form class="d-flex mt-3">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :word, class: "form-control me-2", placeholder: "Search" %>
      <%= button_tag type: "submit", class: "btn btn-outline-secondary text-white" do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </form>
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <div class="d-flex flex-wrap">
        <% @items.each do |item| %>
          (商品イメージがはいります)
          <%= item.name %>
          <%= item.number_to_currency %>
        <% end %>
      </div>
    </div>
  </div>
</div>