config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update] do
      resources :order_details, only: [:update]
    end
  end
  
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    resources :items, only: [:index,:show]
    get 'members/my_page' => 'members#show',as:'my_page'
    get 'members/information/edit' => 'members#edit',as:'members_edit'
    patch 'members/information' => 'members#update',as:'members_update'
    get 'members/confirm' => 'members#confirm',as:'members_confirm'
    patch 'members/withdraw' => 'members#withdraw',as:'members_withdraw'
    resources :cart_items, only: [:index,:update,:create,:destroy]
    delete 'cart_items' => 'cart_items#destroy_all',as:'destroy_all'
    get 'orders/thanks' => 'orders#thanks',as:"orders_thanks"
    resources :orders, only: [:new,:create,:index,:show]
    post 'orders/confirm' => 'orders#confirm',as:"orders_confirm"

    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  get '/searches' => 'searches#search', as:'search'
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :member

  validates :address, presence:true
  validates :postal_code, presence:true
  validates :shipping_name, presence:true
  # エラーメッセージは未実装です(時間に余裕があればつける)

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + shipping_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :member
  belongs_to :item
  
  validates :quantity, numericality: { in: 1..50 }

  def subtotal
  #税込み価格と個数の掛け算です。
    item.with_tax_price.floor*quantity.to_i
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_many :orders, through: :order_items
  belongs_to :genre
  has_one_attached :image

  with_options presence: true do
   validates :name
   validates :introduction
   validates :price
   validates :image
 end
 validates :is_active, inclusion: { in: [true, false] }

  def get_item_image(width,height)
    image.variant(resize_to_limit: [width,height]).processed
  end

  #商品単価の3桁ごとに「,」を表示するメソッドです(税抜)
  #下記のコードはstring型になります。計算には使用できません。(山田)
  #いらないかも、、、
  def number_to_currency
    price.to_s(:delimited)
  end

  #税込み価格の計算です。floorは小数点を表示しないよう記述しております。
  def with_tax_price
    (price*1.1).floor
  end
  
  # 注文商品の合計金額(請求金額　-　送料)
  def sum_of_price
    item.price*quantity
  end

  def self.looks(word)
    @items = Item.where("name LIKE?","%#{word}%")
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence:true
  validates :first_name, presence:true
  validates :last_name_kana, presence:true
  validates :first_name_kana, presence:true
  VALID_POSTAL_CODE_REGEX = /\A\d{7}\z/
  validates :postal_code, presence:true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :address, presence:true
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :phone_number, presence:true, format: { with: VALID_PHONE_REGEX }
  validates :is_deleted, inclusion: [true, false]

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :member

  enum payment_method: ["クレジットカード", "銀行振込"]

  enum order_status: {payment_waiting: 0,  payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
  def set_date
    created_at.strftime("%Y/%-m/%-d/ %-H:%M:%S")
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

  validates :quantity, numericality: { in: 1..50 }
  enum production_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3}

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      redirect_to request.referer
    end

  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @items = Item.looks(params[:word])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_Log_out.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-white bg-info">
    <div class="container">
      <a class="navbar-brand text-white" href="/">
        <span class="h2 text-white font-weight-bold">Nagano Cake</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li><%= link_to about_path, class: "h6 mr-3 text-white" do %>About <% end %> </li>
            <li><%= link_to items_path, class: "h6 mr-3 text-white" do %>商品一覧<% end %></li>
            <li><%= link_to new_member_registration_path, class: "h6 mr-3 text-white" do %>新規登録<% end %></li>
            <li><%= link_to new_member_session_path, class: "h6 text-white" do %>ログイン<% end %></li>
          </ul>
        </div>
        <%= render 'searches/search' %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-white bg-info">
    <div class="container">
      <a class="navbar-brand text-white" href="/">
        <span class="h2 text-white font-weight-bold">Nagano Cake</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="navbar">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li><%= link_to admin_items_path, class: "h6 mr-3 text-white" do %>商品一覧<% end %></li>
            <li><%= link_to admin_members_path, class: "h6 mr-3 text-white" do %>会員一覧<% end %></li>
            <li><%= link_to admin_path, class: "h6 mr-3 text-white" do %>注文履歴一覧<% end %></li>
            <li><%= link_to admin_genres_path, class: "h6 mr-3 text-white" do %>ジャンル一覧<% end %></li>
            <li><%= link_to destroy_admin_session_path, method: :delete, class: "h6 mr-3 text-white" do %>ログアウト<% end %></li>
          </ul>
        </div>
        <%= render 'searches/search' %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_errors.htm.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h4><%= obj.errors.count %> 件のエラー</h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!--<footer class="py-3 bg-info" style="height: 100px;">-->
<!--  <div class="container h-100 align-middle">-->
<!--    <div class="text-center">-->
<!--      <div class="mt-3">-->
<!--      <a class="text-center text-white" style="line-height: 1;" href="/"><span class="text-center">Nagano Cake</span></a>-->
<!--      </div>-->
<!--      <div class="mt-2 mr-4">-->
<!--   　  <span class="copyright text-white text-center" style="line-height: 1; font-size: 10px;">-->
<!--     　 COPYRIGHT © ゆる★から-->
<!--      </span>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</footer>-->

app/views/layouts/_member_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-white bg-info">
    <div class="container">
      <a class="navbar-brand text-white" href="/">
        <span class="h2 text-white font-weight-bold mr-4">Nagano Cake</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if member_signed_in? %>
        <label class="h5 text-white ">ようこそ<%= current_member.last_name %>様！</label>
      <% end %>
      <div class="navbar">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li><%= link_to my_page_path, class: "h6 mr-3 text-white" do %>マイページ<% end %></li>
            <li><%= link_to items_path, class: "h6 mr-3 text-white" do %>商品一覧<% end %></li>
            <li><%= link_to cart_items_path, class: "h6 mr-3 text-white" do %>カート<% end %></li>
            <li><%= link_to destroy_member_session_path, method: :delete, class: "h6 mr-3 text-white" do %>ログアウト<% end %></li>
          </ul>
        </div>
        <%= render 'searches/search' %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if member_signed_in? %>
      <%= render 'layouts/member_header' %>
    <% elsif admin_signed_in? %>
      <%= render 'layouts/admin_header' %>
    <% else %>
      <%= render 'layouts/Log_out' %>
    <% end %>

    <main>
      <%= yield %>
    </main>
    <!--footerはコメントアウトで非表示してます（西宮）-->
    <%= render 'layouts/footer' %>
  </body>
</html>